# Generated by Django 2.0.7 on 2018-07-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20180715_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='deptno',
            field=models.IntegerField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emp',
            name='deptno',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='empno',
            field=models.IntegerField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
