# Generated by Django 2.0.7 on 2018-07-15 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20180715_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='deptno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emp',
            name='deptno',
            field=models.ForeignKey(blank=True, db_column='deptno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app01.Dept'),
        ),
        migrations.AlterField(
            model_name='emp',
            name='empno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
