# Generated by Django 2.0.7 on 2018-07-15 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20180715_1609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
